services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8180:8080
    environment:
      SSL_MODE: "off"
      PHP_OPCACHE_ENABLE: "1"
